---
- name: playbook
  hosts: all
  become: yes
  roles:
    #- patch
    #- users
    #- nginx
    #- packages
    #- docker-compose
    #- docker
    #- sonarqube
    #- mysql
    #- postgres
    #- mongodb
    - jenkins

   
